name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      - name: Install workspaces
        run: npm install

      - name: Test all
        if: always()
        run: npm test

      - name: Lint all
        if: always()
        run: npm run lint
